/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        geist: ["var(--font-geist)", "sans-serif"],
      },
      fontSize: {
        "step--2": "var(--step--2)",
        "step--1": "var(--step--1)",
        "step-0": "var(--step-0)",
        "step-1": "var(--step-1)",
        "step-2": "var(--step-2)",
        "step-3": "var(--step-3)",
        "step-4": "var(--step-4)",
        "step-5": "var(--step-5)",
        "step-6": "var(--step-6)",
        "step-7": "var(--step-7)",
      },
      letterSpacing: {
        tight: "var(--track-tight)",
        normal: "var(--track-normal)",
        wide: "var(--track-wide)",
        wider: "var(--track-wider)",
      },
      lineHeight: {
        tight: "var(--leading-tight)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
      },
      fontWeight: {
        body: "var(--weight-body)",
        heading: "var(--weight-heading)",
        hero: "var(--weight-hero)",
      },
      colors: {
        brand: {
          bg: "var(--color-bg)",
          "bg-soft": "var(--color-bg-soft)",
          surface: "var(--color-surface)",
          "surface-elevated": "var(--color-surface-elevated)",
          primary: "var(--color-primary)",
          secondary: "var(--color-secondary)",
          "accent-cyan": "var(--color-accent-cyan)",
          "accent-fuchsia": "var(--color-accent-fuchsia)",
          "border-subtle": "var(--color-border-subtle)",
          "border-strong": "var(--color-border-strong)",
          text: "var(--color-text-primary)",
          "text-muted": "var(--color-text-muted)",
        },
      },
      backgroundImage: {
        "brand-aurora": "var(--gradient-aurora)",
        "brand-card": "var(--gradient-card)",
      },
      spacing: {
        xs: "var(--space-xs)",
        sm: "var(--space-sm)",
        md: "var(--space-md)",
        lg: "var(--space-lg)",
        xl: "var(--space-xl)",
        "2xl": "var(--space-2xl)",
        "3xl": "var(--space-3xl)",
        "4xl": "var(--space-4xl)",
        "5xl": "var(--space-5xl)",
        "6xl": "var(--space-6xl)",
        "space-1": "var(--space-1)",
        "space-2": "var(--space-2)",
        "space-3": "var(--space-3)",
        "space-4": "var(--space-4)",
        "space-5": "var(--space-5)",
        "space-6": "var(--space-6)",
        "space-7": "var(--space-7)",
        "space-8": "var(--space-8)",
        "space-9": "var(--space-9)",
        "space-10": "var(--space-10)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        max: "var(--radius-max)",
      },
      boxShadow: {
        "ambient-soft": "var(--shadow-ambient-soft)",
        elevated: "var(--shadow-elevated)",
        "border-soft": "var(--shadow-border-soft)",
        "glow-cyan": "var(--glow-cyan)",
        "glow-fuchsia": "var(--glow-fuchsia)",
        "ring-soft": "var(--glow-ring-soft)",
      },
      maxWidth: {
        "page-max": "var(--layout-page-max)",
        "container-sm": "var(--container-sm)",
        "container-md": "var(--container-md)",
        "container-lg": "var(--container-lg)",
        "container-xl": "var(--container-xl)",
      },
    },
  },
  screens: {
    xs: "20rem",
    sm: "24rem",
    md: "30rem",
    lg: "48rem",
    xl: "64rem",
    "2xl": "80rem",
  },
};