-- Add all missing columns to products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS version INT DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS compare_at_price DECIMAL(10,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_per_item DECIMAL(10,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'INR';
ALTER TABLE products ADD COLUMN IF NOT EXISTS taxable BOOLEAN DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS inventory_mode VARCHAR(10) DEFAULT 'SINGLE';
ALTER TABLE products ADD COLUMN IF NOT EXISTS track_inventory BOOLEAN DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS continue_selling_when_out_of_stock BOOLEAN DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_threshold INT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS category VARCHAR(50);
