import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1770026319664 implements MigrationInterface {
    name = 'InitialSchema1770026319664'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" text NOT NULL, "expires_at" TIMESTAMP NOT NULL, "revoked_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "oauth_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" character varying NOT NULL, "provider_user_id" text NOT NULL, "email" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710a81523f515b78f894e33bb10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ea7720e04e3ae1278575c3159c" ON "oauth_accounts" ("provider", "provider_user_id") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "product_id" character varying NOT NULL, "variant_id" character varying NOT NULL, "product_name_snapshot" character varying NOT NULL, "variant_label_snapshot" character varying NOT NULL, "sku_snapshot" character varying NOT NULL, "image_url_snapshot" character varying, "quantity" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "line_total" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "full_name" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying NOT NULL, "address_line_1" character varying NOT NULL, "address_line_2" character varying, "landmark" character varying, "city" character varying NOT NULL, "state" character varying NOT NULL, "postal_code" character varying NOT NULL, "country" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c0c1dd40c342dd0afbfd63b44c5" UNIQUE ("order_id"), CONSTRAINT "REL_c0c1dd40c342dd0afbfd63b44c" UNIQUE ("order_id"), CONSTRAINT "PK_4b8d293512b266903d636106440" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('initiated', 'pending', 'authorized', 'captured', 'failed')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "provider" character varying NOT NULL DEFAULT 'razorpay', "provider_payment_id" character varying, "provider_order_id" character varying, "amount" numeric(10,2) NOT NULL, "refunded_amount" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'INR', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'initiated', "payment_method" character varying, "failure_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum" AS ENUM('shipped', 'delivered')`);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "carrier" character varying, "tracking_number" character varying, "status" "public"."shipments_status_enum" NOT NULL DEFAULT 'shipped', "shipped_at" TIMESTAMP, "delivered_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "from_status" character varying, "to_status" character varying NOT NULL, "changed_by" character varying, "reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6c66d853f155531985fc4f6ec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending_payment', 'payment_failed', 'processing', 'shipped', 'delivered', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_number" character varying NOT NULL, "user_id" uuid, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending_payment', "payment_order_id" character varying, "subtotal" numeric(10,2) NOT NULL, "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "shipping_amount" numeric(10,2) NOT NULL DEFAULT '0', "discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "total_amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'INR', "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_75eba1c6b1a66b09f2a97e6927b" UNIQUE ("order_number"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ORDERS_STATUS_CREATED" ON "orders" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORDERS_USER_ID" ON "orders" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "ticket_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid NOT NULL, "user_id" uuid NOT NULL, "message" text NOT NULL, "is_admin_reply" boolean NOT NULL DEFAULT false, "attachments" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_37beb692dedf7eccb4e519ccec1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid NOT NULL, "from_status" character varying(20), "to_status" character varying(20) NOT NULL, "changed_by" uuid NOT NULL, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d989dae9e6078a6d4ce1aca63f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('open', 'in_progress', 'waiting_on_customer', 'resolved', 'closed')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_number" character varying(32) NOT NULL, "order_id" uuid NOT NULL, "user_id" uuid NOT NULL, "assigned_to" uuid, "category" character varying(50) NOT NULL, "subject" character varying(200) NOT NULL, "description" text NOT NULL, "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'open', "priority" character varying(20) NOT NULL DEFAULT 'medium', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "resolved_at" TIMESTAMP, "closed_at" TIMESTAMP, CONSTRAINT "UQ_8d7b9a157280caf57aa0282e72c" UNIQUE ("ticket_number"), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipping_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "full_name" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "house_number" character varying(100) NOT NULL, "address" character varying(500) NOT NULL, "landmark" character varying(255), "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "postal_code" character varying(20) NOT NULL, "country" character varying(100) NOT NULL DEFAULT 'India', "address_type" character varying(20) NOT NULL DEFAULT 'home', "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_cced78984eddbbe24470f226692" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique_default_address_per_user" ON "shipping_addresses" ("user_id") WHERE is_default = true AND deleted_at IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_shipping_postal_code" ON "shipping_addresses" ("postal_code") `);
        await queryRunner.query(`CREATE INDEX "idx_shipping_user_id" ON "shipping_addresses" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "auth_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" text, "auth_provider" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "role" character varying NOT NULL DEFAULT 'USER', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "last_login_at" TIMESTAMP, CONSTRAINT "UQ_13d8b49e55a8b06bee6bbc828fb" UNIQUE ("email"), CONSTRAINT "PK_c88cc8077366b470dafc2917366" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auth_user_id" uuid NOT NULL, "full_name" character varying NOT NULL, "phone" character varying, "avatar_url" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0182bd232f7cd50face0b8340de" UNIQUE ("auth_user_id"), CONSTRAINT "REL_0182bd232f7cd50face0b8340d" UNIQUE ("auth_user_id"), CONSTRAINT "PK_1ec6662219f4605723f1e41b6cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "user_email" character varying(255) NOT NULL, "event_type" character varying(50) NOT NULL, "entity_type" character varying(50) NOT NULL, "entity_id" character varying(255), "entity_name" character varying(255), "before" jsonb, "after" jsonb, "changes" jsonb, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d9956e3844c44880dcdefe80692" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings_version" ("id" integer NOT NULL DEFAULT '1', "version" bigint NOT NULL DEFAULT '1', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_11e692f94cf197b408a0043a6fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(255) NOT NULL, "value" jsonb NOT NULL, "environment" character varying(20) NOT NULL DEFAULT 'production', "section" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "is_published" boolean NOT NULL DEFAULT true, "version" integer NOT NULL DEFAULT '1', "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "setting_id" uuid NOT NULL, "key" character varying(255) NOT NULL, "value" jsonb NOT NULL, "environment" character varying(20) NOT NULL, "changed_by" uuid, "change_reason" text, "previous_version" integer NOT NULL, "changed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a28fc82c541fd112ebcaef8d3a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "sku" character varying(100) NOT NULL, "sku_locked" boolean NOT NULL DEFAULT false, "size" character varying(50) NOT NULL, "price" numeric(10,2) NOT NULL, "price_override" numeric(10,2), "stock_quantity" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_46f236f21640f9da218a063a866" UNIQUE ("sku"), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PRODUCT_VARIANTS_PRODUCT_ID" ON "product_variants" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_PRODUCT_VARIANTS_SKU" ON "product_variants" ("sku") `);
        await queryRunner.query(`CREATE INDEX "idx_variants_stock" ON "product_variants" ("product_id", "is_active", "stock_quantity") `);
        await queryRunner.query(`CREATE TYPE "public"."product_images_status_enum" AS ENUM('TEMP', 'ACTIVE')`);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "url" text NOT NULL, "alt_text" character varying(255), "status" "public"."product_images_status_enum" NOT NULL DEFAULT 'TEMP', "is_primary" boolean NOT NULL DEFAULT false, "display_order" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PRODUCT_IMAGES_PRODUCT_ID" ON "product_images" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_images_active" ON "product_images" ("product_id", "status", "is_primary", "display_order") `);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "public"."products_inventory_mode_enum" AS ENUM('SINGLE', 'VARIANT')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "status" "public"."products_status_enum" NOT NULL DEFAULT 'DRAFT', "version" integer NOT NULL, "base_price" numeric(10,2) NOT NULL, "compare_at_price" numeric(10,2), "cost_per_item" numeric(10,2), "currency" character varying(3) NOT NULL DEFAULT 'INR', "taxable" boolean NOT NULL DEFAULT true, "inventory_mode" "public"."products_inventory_mode_enum" NOT NULL DEFAULT 'SINGLE', "track_inventory" boolean NOT NULL DEFAULT true, "sku" character varying(100), "stock_quantity" integer NOT NULL DEFAULT '0', "continue_selling_when_out_of_stock" boolean NOT NULL DEFAULT false, "low_stock_threshold" integer, "is_featured" boolean NOT NULL DEFAULT false, "product_type" character varying(50) NOT NULL DEFAULT 'T-Shirt', "category" character varying(50) NOT NULL DEFAULT 'Drop 1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PRODUCTS_SLUG" ON "products" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_PRODUCTS_IS_FEATURED" ON "products" ("is_featured") `);
        await queryRunner.query(`CREATE INDEX "idx_products_low_stock" ON "products" ("track_inventory", "stock_quantity", "low_stock_threshold") `);
        await queryRunner.query(`CREATE INDEX "idx_products_featured_active" ON "products" ("is_featured", "status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "product_collection_map" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "collection_id" uuid NOT NULL, "position" integer NOT NULL DEFAULT '0', "added_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cbc0330c8c02bb0f06ecc8d7627" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PCM_PRODUCT_ID" ON "product_collection_map" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_PCM_COLLECTION_ID" ON "product_collection_map" ("collection_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pcm_collection_position" ON "product_collection_map" ("collection_id", "position") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique_product_collection" ON "product_collection_map" ("product_id", "collection_id") `);
        await queryRunner.query(`CREATE TABLE "collections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, "scheduled_start" TIMESTAMP, "scheduled_end" TIMESTAMP, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ed225078e8bf65b448b69105b45" UNIQUE ("name"), CONSTRAINT "UQ_99d0d14f9f23b45d2c6648c4b57" UNIQUE ("slug"), CONSTRAINT "PK_21c00b1ebbd41ba1354242c5c4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_COLLECTIONS_NAME" ON "collections" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_COLLECTIONS_SLUG" ON "collections" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_collections_active" ON "collections" ("is_active", "scheduled_start", "scheduled_end") `);
        await queryRunner.query(`CREATE TYPE "public"."discount_target_groups_group_type_enum" AS ENUM('COLLECTION', 'TYPE', 'CATEGORY', 'PRODUCT')`);
        await queryRunner.query(`CREATE TABLE "discount_target_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "discount_id" uuid NOT NULL, "group_type" "public"."discount_target_groups_group_type_enum" NOT NULL, "group_value_uuid" uuid, "group_value_text" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d9c432a0371d403284ea9b6aad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "discount_usages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "discount_id" uuid NOT NULL, "user_id" uuid, "order_id" uuid NOT NULL, "used_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_914f6ae7aa31821ed0101b5f302" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_type_enum" AS ENUM('PERCENT', 'FLAT')`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_scope_enum" AS ENUM('PRODUCT', 'GROUP', 'GLOBAL')`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_audience_enum" AS ENUM('ALL', 'NEW', 'TOP', 'FREQUENT')`);
        await queryRunner.query(`CREATE TABLE "discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(50) NOT NULL, "description" text, "type" "public"."discounts_type_enum" NOT NULL DEFAULT 'PERCENT', "value" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'INR', "scope" "public"."discounts_scope_enum" NOT NULL DEFAULT 'PRODUCT', "audience" "public"."discounts_audience_enum" NOT NULL DEFAULT 'ALL', "min_order_amount" numeric(10,2) NOT NULL DEFAULT '0', "min_user_orders" integer NOT NULL DEFAULT '0', "min_user_ltv" numeric(10,2) NOT NULL DEFAULT '0', "global_usage_limit" integer, "per_user_limit" integer NOT NULL DEFAULT '1', "priority" integer NOT NULL DEFAULT '1', "is_stackable" boolean NOT NULL DEFAULT false, "max_stack_count" integer NOT NULL DEFAULT '1', "start_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "end_date" TIMESTAMP WITH TIME ZONE, "is_active" boolean NOT NULL DEFAULT true, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8c7cc2340e9ea0fc5a246e63749" UNIQUE ("code"), CONSTRAINT "PK_66c522004212dc814d6e2f14ecc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_discounts_code" ON "discounts" ("code") `);
        await queryRunner.query(`CREATE INDEX "idx_discounts_active_lookup" ON "discounts" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "order_discounts" ("order_id" uuid NOT NULL, "discount_id" uuid NOT NULL, "discount_code" character varying(50) NOT NULL, "discount_type" character varying(20) NOT NULL, "discount_value" numeric(10,2) NOT NULL, "applied_amount" numeric(10,2) NOT NULL, CONSTRAINT "PK_a7418714ffceebc125bf6d8fcfe" PRIMARY KEY ("order_id", "discount_id"))`);
        await queryRunner.query(`CREATE TABLE "email_otp_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "otp_hash" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, "attempt_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2b62eb55be3a64f65ed1b0c41cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_513c4c020e55f5d3d4333279df" ON "email_otp_codes" ("email", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_23ebf9ba44bb12b9c31621d10d" ON "email_otp_codes" ("email", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_901a374710fdcec83707b3684a" ON "email_otp_codes" ("email", "used_at") `);
        await queryRunner.query(`CREATE TABLE "login_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "user_email" character varying(255) NOT NULL, "user_type" character varying(20) NOT NULL, "event_type" character varying(50) NOT NULL, "login_method" character varying(50), "ip_address" character varying(45) NOT NULL, "user_agent" text, "success" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4c11c283d96d25b3879e6ccb29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cart_id" uuid NOT NULL, "product_id" uuid, "variant_id" uuid, "quantity" integer NOT NULL, "price_snapshot" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'INR', "product_title" text, "product_image" text, "variant_label" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_CART_ITEMS_CART_ID" ON "cart_items" ("cart_id") `);
        await queryRunner.query(`CREATE TYPE "public"."carts_status_enum" AS ENUM('ACTIVE', 'ORDERED')`);
        await queryRunner.query(`CREATE TABLE "carts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "status" "public"."carts_status_enum" NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admin_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admin_id" uuid NOT NULL, "admin_email" character varying(255) NOT NULL, "event_type" character varying(100) NOT NULL, "entity_type" character varying(50) NOT NULL, "entity_id" character varying(255) NOT NULL, "entity_name" character varying(255), "before" jsonb, "after" jsonb, "changes" jsonb, "ip_address" character varying(45) NOT NULL, "user_agent" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de7a8fc2fbb525484c71a86bb96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_notifications_type_enum" AS ENUM('ORDER_CONFIRMATION', 'ORDER_FULFILLED')`);
        await queryRunner.query(`CREATE TABLE "order_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "type" "public"."order_notifications_type_enum" NOT NULL, "recipient" character varying NOT NULL, "sent_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_85e9427cbcf1634c68846e12ec7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_53b6c4bfc78a9ac45bb8615825" ON "order_notifications" ("order_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."background_jobs_status_enum" AS ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "background_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_name" character varying(100) NOT NULL, "job_type" character varying(50) NOT NULL, "status" "public"."background_jobs_status_enum" NOT NULL DEFAULT 'PENDING', "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "duration_ms" integer, "error_message" text, "error_stack" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1f31731b1a02806c4aa631acb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_BACKGROUND_JOBS_JOB_NAME" ON "background_jobs" ("job_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_BACKGROUND_JOBS_STATUS" ON "background_jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_BACKGROUND_JOBS_STARTED_AT" ON "background_jobs" ("started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_BACKGROUND_JOBS_CREATED_AT" ON "background_jobs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admin_id" uuid NOT NULL, "admin_email" character varying(255) NOT NULL, "event_type" character varying(50) NOT NULL, "entity_type" character varying(50) NOT NULL, "entity_id" character varying(255), "before" jsonb, "after" jsonb, "changes" jsonb, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_LOGS_ADMIN_ID" ON "audit_logs" ("admin_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_LOGS_EVENT_TYPE" ON "audit_logs" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_LOGS_ENTITY_TYPE" ON "audit_logs" ("entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_LOGS_ENTITY_ID" ON "audit_logs" ("entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIT_LOGS_CREATED_AT" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "email_otp_codes" DROP COLUMN "attempt_count"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "setting_id"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "environment"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "changed_by"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "change_reason"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "previous_version"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "changed_at"`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "setting_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "key" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "value" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "environment" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "changed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "change_reason" text`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "previous_version" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "changed_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_otp_codes" ADD "attempt_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "admin_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "settings" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "is_active" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "validation_passed" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "test_passed" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_otp_codes" DROP COLUMN "otp_hash"`);
        await queryRunner.query(`ALTER TABLE "email_otp_codes" ADD "otp_hash" text NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_SETTINGS_HISTORY_IS_ACTIVE" ON "settings_history" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_SETTINGS_HISTORY_CREATED_AT" ON "settings_history" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" ADD CONSTRAINT "FK_22a05e92f51a983475f9281d3b0" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_addresses" ADD CONSTRAINT "FK_c0c1dd40c342dd0afbfd63b44c5" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_e86fac2a18a75dcb82bfbb23f43" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_messages" ADD CONSTRAINT "FK_75b3a5f421dbf7b73778da519cb" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_messages" ADD CONSTRAINT "FK_1855fc5d18f5a461465929dab43" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_status_history" ADD CONSTRAINT "FK_52fa10cddeab4cf9d490c387a6c" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_status_history" ADD CONSTRAINT "FK_1b80e7fcc35d804f1a7492bfab2" FOREIGN KEY ("changed_by") REFERENCES "auth_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_bd5636236f799b19f132abf8d70" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_2e445270177206a97921e461710" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_47c3fba35bfcbb08e3445f57d6e" FOREIGN KEY ("assigned_to") REFERENCES "auth_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_addresses" ADD CONSTRAINT "FK_75ab21980cabc5be328df3e49cc" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_0182bd232f7cd50face0b8340de" FOREIGN KEY ("auth_user_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_audit_logs" ADD CONSTRAINT "FK_b45c5e4d92b4f9be4278f340017" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_collection_map" ADD CONSTRAINT "FK_d7aa05d9a2526f5afe11d2ac441" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_collection_map" ADD CONSTRAINT "FK_bce345704be559582fb1da14273" FOREIGN KEY ("collection_id") REFERENCES "collections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_target_groups" ADD CONSTRAINT "FK_fb004e198061c36880eed0dd00a" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_target_groups" ADD CONSTRAINT "FK_3aa2e859f9517bc6a96ea0f6ad0" FOREIGN KEY ("group_value_uuid") REFERENCES "collections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_usages" ADD CONSTRAINT "FK_e522ffed68f1b6f1b5c64279d03" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_usages" ADD CONSTRAINT "FK_e0da83bf135cebda03010aea34f" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_discounts" ADD CONSTRAINT "FK_e7b488cebe333f449398769b2cc" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_discounts" ADD CONSTRAINT "FK_0fc1ec4e3db9001ad60c19daf16" FOREIGN KEY ("discount_id") REFERENCES "discounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "login_audit_logs" ADD CONSTRAINT "FK_4ac92d4507167cc41607d4a9f54" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_6385a745d9e12a89b859bb25623" FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_30e89257a105eab7648a35c7fce" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_ede780fc2b865d1d1323e598038" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea" FOREIGN KEY ("user_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_audit_logs" ADD CONSTRAINT "FK_01a78e07962ed72eaf9ccae990b" FOREIGN KEY ("admin_id") REFERENCES "auth_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD CONSTRAINT "FK_51066e205ec90a1cf7905c998af" FOREIGN KEY ("admin_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_notifications" ADD CONSTRAINT "FK_e3b588e22abc79e42113386ab04" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_b29de603374cbfa7d776d88e5b5" FOREIGN KEY ("admin_id") REFERENCES "auth_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_b29de603374cbfa7d776d88e5b5"`);
        await queryRunner.query(`ALTER TABLE "order_notifications" DROP CONSTRAINT "FK_e3b588e22abc79e42113386ab04"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP CONSTRAINT "FK_51066e205ec90a1cf7905c998af"`);
        await queryRunner.query(`ALTER TABLE "admin_audit_logs" DROP CONSTRAINT "FK_01a78e07962ed72eaf9ccae990b"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_ede780fc2b865d1d1323e598038"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_30e89257a105eab7648a35c7fce"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_6385a745d9e12a89b859bb25623"`);
        await queryRunner.query(`ALTER TABLE "login_audit_logs" DROP CONSTRAINT "FK_4ac92d4507167cc41607d4a9f54"`);
        await queryRunner.query(`ALTER TABLE "order_discounts" DROP CONSTRAINT "FK_0fc1ec4e3db9001ad60c19daf16"`);
        await queryRunner.query(`ALTER TABLE "order_discounts" DROP CONSTRAINT "FK_e7b488cebe333f449398769b2cc"`);
        await queryRunner.query(`ALTER TABLE "discount_usages" DROP CONSTRAINT "FK_e0da83bf135cebda03010aea34f"`);
        await queryRunner.query(`ALTER TABLE "discount_usages" DROP CONSTRAINT "FK_e522ffed68f1b6f1b5c64279d03"`);
        await queryRunner.query(`ALTER TABLE "discount_target_groups" DROP CONSTRAINT "FK_3aa2e859f9517bc6a96ea0f6ad0"`);
        await queryRunner.query(`ALTER TABLE "discount_target_groups" DROP CONSTRAINT "FK_fb004e198061c36880eed0dd00a"`);
        await queryRunner.query(`ALTER TABLE "product_collection_map" DROP CONSTRAINT "FK_bce345704be559582fb1da14273"`);
        await queryRunner.query(`ALTER TABLE "product_collection_map" DROP CONSTRAINT "FK_d7aa05d9a2526f5afe11d2ac441"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "user_audit_logs" DROP CONSTRAINT "FK_b45c5e4d92b4f9be4278f340017"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_0182bd232f7cd50face0b8340de"`);
        await queryRunner.query(`ALTER TABLE "shipping_addresses" DROP CONSTRAINT "FK_75ab21980cabc5be328df3e49cc"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_47c3fba35bfcbb08e3445f57d6e"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_2e445270177206a97921e461710"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_bd5636236f799b19f132abf8d70"`);
        await queryRunner.query(`ALTER TABLE "ticket_status_history" DROP CONSTRAINT "FK_1b80e7fcc35d804f1a7492bfab2"`);
        await queryRunner.query(`ALTER TABLE "ticket_status_history" DROP CONSTRAINT "FK_52fa10cddeab4cf9d490c387a6c"`);
        await queryRunner.query(`ALTER TABLE "ticket_messages" DROP CONSTRAINT "FK_1855fc5d18f5a461465929dab43"`);
        await queryRunner.query(`ALTER TABLE "ticket_messages" DROP CONSTRAINT "FK_75b3a5f421dbf7b73778da519cb"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_e86fac2a18a75dcb82bfbb23f43"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "order_addresses" DROP CONSTRAINT "FK_c0c1dd40c342dd0afbfd63b44c5"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" DROP CONSTRAINT "FK_22a05e92f51a983475f9281d3b0"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SETTINGS_HISTORY_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SETTINGS_HISTORY_IS_ACTIVE"`);
        await queryRunner.query(`ALTER TABLE "email_otp_codes" DROP COLUMN "otp_hash"`);
        await queryRunner.query(`ALTER TABLE "email_otp_codes" ADD "otp_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "test_passed"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "validation_passed"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "settings"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "admin_id"`);
        await queryRunner.query(`ALTER TABLE "email_otp_codes" DROP COLUMN "attempt_count"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "changed_at"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "previous_version"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "change_reason"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "changed_by"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "environment"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "settings_history" DROP COLUMN "setting_id"`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "changed_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "previous_version" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "change_reason" text`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "changed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "environment" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "value" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "key" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings_history" ADD "setting_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_otp_codes" ADD "attempt_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_LOGS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_LOGS_ENTITY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_LOGS_ENTITY_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_LOGS_EVENT_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AUDIT_LOGS_ADMIN_ID"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BACKGROUND_JOBS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BACKGROUND_JOBS_STARTED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BACKGROUND_JOBS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BACKGROUND_JOBS_JOB_NAME"`);
        await queryRunner.query(`DROP TABLE "background_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."background_jobs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53b6c4bfc78a9ac45bb8615825"`);
        await queryRunner.query(`DROP TABLE "order_notifications"`);
        await queryRunner.query(`DROP TYPE "public"."order_notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "admin_audit_logs"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP TYPE "public"."carts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CART_ITEMS_CART_ID"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP TABLE "login_audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_901a374710fdcec83707b3684a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23ebf9ba44bb12b9c31621d10d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_513c4c020e55f5d3d4333279df"`);
        await queryRunner.query(`DROP TABLE "email_otp_codes"`);
        await queryRunner.query(`DROP TABLE "order_discounts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_discounts_active_lookup"`);
        await queryRunner.query(`DROP INDEX "public"."idx_discounts_code"`);
        await queryRunner.query(`DROP TABLE "discounts"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_audience_enum"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_scope_enum"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_type_enum"`);
        await queryRunner.query(`DROP TABLE "discount_usages"`);
        await queryRunner.query(`DROP TABLE "discount_target_groups"`);
        await queryRunner.query(`DROP TYPE "public"."discount_target_groups_group_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_collections_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_COLLECTIONS_SLUG"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_COLLECTIONS_NAME"`);
        await queryRunner.query(`DROP TABLE "collections"`);
        await queryRunner.query(`DROP INDEX "public"."unique_product_collection"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pcm_collection_position"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PCM_COLLECTION_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PCM_PRODUCT_ID"`);
        await queryRunner.query(`DROP TABLE "product_collection_map"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_featured_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_low_stock"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRODUCTS_IS_FEATURED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRODUCTS_SLUG"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_inventory_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_images_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRODUCT_IMAGES_PRODUCT_ID"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP TYPE "public"."product_images_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_variants_stock"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRODUCT_VARIANTS_SKU"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRODUCT_VARIANTS_PRODUCT_ID"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "settings_history"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "settings_version"`);
        await queryRunner.query(`DROP TABLE "user_audit_logs"`);
        await queryRunner.query(`DROP TABLE "user_profiles"`);
        await queryRunner.query(`DROP TABLE "auth_users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shipping_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shipping_postal_code"`);
        await queryRunner.query(`DROP INDEX "public"."unique_default_address_per_user"`);
        await queryRunner.query(`DROP TABLE "shipping_addresses"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP TABLE "ticket_status_history"`);
        await queryRunner.query(`DROP TABLE "ticket_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORDERS_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORDERS_STATUS_CREATED"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_status_history"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_addresses"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea7720e04e3ae1278575c3159c"`);
        await queryRunner.query(`DROP TABLE "oauth_accounts"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
    }

}
