/**
 * Audit Event Types
 * Comprehensive taxonomy of all admin actions
 */
export enum AuditEventType {
    // Products
    PRODUCT_CREATED = 'PRODUCT_CREATED',
    PRODUCT_UPDATED = 'PRODUCT_UPDATED',
    PRODUCT_DELETED = 'PRODUCT_DELETED',
    PRODUCT_STATUS_CHANGED = 'PRODUCT_STATUS_CHANGED',
    PRODUCT_PRICE_CHANGED = 'PRODUCT_PRICE_CHANGED',
    PRODUCT_STOCK_CHANGED = 'PRODUCT_STOCK_CHANGED',
    PRODUCT_PUBLISHED = 'PRODUCT_PUBLISHED',
    PRODUCT_ARCHIVED = 'PRODUCT_ARCHIVED',

    // Variants
    VARIANT_CREATED = 'VARIANT_CREATED',
    VARIANT_UPDATED = 'VARIANT_UPDATED',
    VARIANT_DELETED = 'VARIANT_DELETED',
    VARIANT_SKU_CHANGED = 'VARIANT_SKU_CHANGED',

    // Orders
    ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
    ORDER_CANCELLED = 'ORDER_CANCELLED',
    ORDER_REFUNDED = 'ORDER_REFUNDED',
    ORDER_FULFILLED = 'ORDER_FULFILLED',

    // Customers
    CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
    CUSTOMER_DELETED = 'CUSTOMER_DELETED',
    CUSTOMER_BLOCKED = 'CUSTOMER_BLOCKED',

    // Settings
    SETTINGS_UPDATED = 'SETTINGS_UPDATED',
    PAYMENT_CONFIG_CHANGED = 'PAYMENT_CONFIG_CHANGED',
    SHIPPING_CONFIG_CHANGED = 'SHIPPING_CONFIG_CHANGED',
    NOTIFICATION_CONFIG_CHANGED = 'NOTIFICATION_CONFIG_CHANGED',

    // Admin & Auth
    ADMIN_LOGIN = 'ADMIN_LOGIN',
    ADMIN_LOGOUT = 'ADMIN_LOGOUT',
    ADMIN_ROLE_CHANGED = 'ADMIN_ROLE_CHANGED',
    ADMIN_CREATED = 'ADMIN_CREATED',
    ADMIN_DELETED = 'ADMIN_DELETED',

    // System
    BULK_OPERATION = 'BULK_OPERATION',
    DATA_EXPORT = 'DATA_EXPORT',
    DATA_IMPORT = 'DATA_IMPORT',
}

/**
 * Entity Types
 */
export enum AuditEntityType {
    PRODUCT = 'product',
    VARIANT = 'variant',
    ORDER = 'order',
    CUSTOMER = 'customer',
    SETTINGS = 'settings',
    ADMIN = 'admin',
    SYSTEM = 'system',
}
